# Bluetooth keyboard name (max 16 characters)
CONFIG_ZMK_KEYBOARD_NAME="iPhone17ProMax"

# RGB off by default (toggle on with RGB_TOG)
CONFIG_ZMK_RGB_UNDERGLOW_ON_START=n

# Bluetooth connection stability
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Enable mouse emulation.
# CONFIG_ZMK_POINTING=y

# Change idle settings
# CONFIG_ZMK_IDLE_TIMEOUT=30000

# Deep sleep settings
# CONFIG_ZMK_SLEEP=y
# CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000
